# config/routes.yaml

# Cette configuration indique à Symfony d'aller chercher 
# les routes définies par des attributs (#[Route]) dans tes contrôleurs.
controllers:
    resource: ../src/Controller/
    type: attribute

# Si tu as d'autres routes spécifiques, elles s'ajouteront en dessous.